config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'campaigns#index'
  resources :campaigns, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
# frozen_string_literal: true

class Campaign < ApplicationRecord
  validates :title, :description, :state, :publication_date, :position, presence: true
  enum state: {
    draft: 0,
    published: 1,
    archived: 2
  }
  scope :states_keys, -> { states.keys }
  scope :ordered_by_state_and_position, lambda {
    in_order_of(:state, %w[published draft archived]).order(position: :desc)
  }

  def humanized_title
    title.humanize
  end

  def humanized_state
    state.humanize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campaigns_controller.rb
# frozen_string_literal: true

class CampaignsController < ApplicationController
  def index
    @campaigns = Campaign.ordered_by_state_and_position
  end

  def show
    @campaign = Campaign.find(params[:id])
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date)
    date.strftime('%d/%m/%Y at %I:%M%p')
  end

  def badge(color)
    "bg-#{color}-100 px-[0.65em] pb-[0.25em] pt-[0.35em] text-center
      align-baseline text-[0.75em] font-bold leading-none text-#{color}-600"
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def state_badge(item)
    return '' unless item.state.present?

    color_state_hash = { orange: item.draft?, green: item.published?, gray: item.archived? }
    bg_color = class_names('bg-', color_state_hash, '-100').delete(' ')
    text_color = class_names('text-', color_state_hash, '-600').delete(' ')
    "#{bg_color} px-[0.65em] pb-[0.25em] pt-[0.35em] text-center
      align-baseline text-[0.75em] font-bold leading-none #{text_color}"
  end
end

app/views/campaigns/index.html.erb
<%= turbo_frame_tag "modal_frame" do %>
  <div id="modal" class="hidden fixed inset-0 bg-gray-500 bg-opacity-75 overflow-y-auto">
    <div class="container mx-auto p-4 max-w-md">
      <!-- Modal content will be loaded here -->
    </div>
  </div>
<% end %>


<div class="w-full xl:w-8/12 mb-12 xl:mb-0 px-4 mx-auto mt-12">
  <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-lg rounded ">
    <div class="rounded-t mb-0 px-4 py-3 border-0">
      <div class="flex flex-wrap items-center">
        <div class="relative w-full px-4 max-w-full flex-grow flex-1">
          <h3 class="font-semibold text-base text-blueGray-700">Campaigns</h3>
        </div>
      </div>
    </div>

    <div class="block w-full overflow-x-auto">
      <table class="items-center bg-transparent w-full border-collapse ">
        <thead>
        <tr>
          <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
            Title
          </th>
          <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
            State
          </th>
        </tr>
        </thead>
        <tbody>
          <% @campaigns.each do |campaign| %>
            <%= render 'campaigns/partials/campaign_table_row', campaign: campaign %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/campaigns/partials/_campaign_table_row.html.erb
<tr id="tr-<%= campaign.id %>" class="cursor-pointer hover:bg-gray-100">
  <th class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left text-blueGray-700 ">
    <%= link_to campaign.humanized_title, campaign_path(campaign), data: { turbo_frame: "modal_frame" }, class: "stretched-link", id: "desc-#{campaign.id}" %>
  </th>
  <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
    <span class="inline-block whitespace-nowrap rounded-full <%= state_badge(campaign)%>"><%= campaign.humanized_state %></span>
  </td>
</tr>

app/views/campaigns/show.html.erb
<%= turbo_frame_tag "modal_frame" do %>
  <div  id="modal" data-controller="modal" data-action="click->modal#close" class="fixed inset-0 flex items-center justify-center z-50 bg-gray-500 bg-opacity-75 overflow-y-auto">
    <div class="bg-white rounded-lg p-6 w-96 max-w-full shadow-lg transform transition-all duration-300">
      <!-- Modal Header -->
      <div class="flex justify-between items-center border-b-2 border-gray-200 pb-4">
        <div class="flex justify-between items-center">
          <h2 class="text-xl font-semibold"><%= @campaign.humanized_title %></h2>
          <span class="ml-1 inline-block whitespace-nowrap rounded-full <%= state_badge(@campaign) %>"><%= @campaign.humanized_state %></span>
        </div>
        <button class="text-gray-500 hover:text-gray-700 focus:outline-none" data-controller="modal" data-action="click->modal#close">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x">
            <line x1="18" y1="6" x2="6" y2="18"></line>
            <line x1="6" y1="6" x2="18" y2="18"></line>
          </svg>
        </button>
      </div>

      <!-- Modal Content -->
      <div class="mt-6 space-y-4">
        <p class="text-md text-gray-600"><%= @campaign.description %></p>
        <div class="flex flex-col space-y-4">

        </div>
      </div>

      <!-- Additional Information -->
      <div class="mt-6 text-sm text-gray-500">
        <p>Published on: <%= format_date(@campaign.publication_date) %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GocertifyCampaigns</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="turbo-visit-control" content="reload">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/styles/tailwind.css">
    <link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css">
  </head>

  <body class="bg-blueGray-50">
    <main class="container mx-auto px-4 sm:px-8">
      <%= yield %>
    </main>
  </body>
</html>